name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'lucksoft-yungui/chat-server'
        
    - name: Extract branch name
      shell: bash
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        cd apps/meteor/.docker
        docker build -t lucksoft/update-server:${VERSION} .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push lucksoft/update-server:${VERSION}
